### ISSUE TITLE
How to use it as you?

### ISSUE THREAD

**Issue by toprak** [Ajatt-Tools/manyame#1]
Firstly, I want to thank you for creating this. I just wonder you just typed "manyame" on linux terminal, As a linux beginner I really wonder how did you do I am a bit lazy to do ./manyame.sh :D Also, I can not select as batch?
Regards

**Comment by whew** [comment]
I recorded a video on Windows 7, you can run a bat file there just by typing its name. If you want to run the sh file like that on Linux, you need to put manyame.sh in $PATH and remove ".sh" from the name.

>Also, I can not select as batch?
Both the script in the repository and the latest Windows Release zip are configured so that you can batch download. Just press 'Tab' near that episodes that you want to dl and don't enter episode number if you want to batch dl various episodes.
